dist: trusty

language: python

python:
    - '2.7'
    - '3.6'

before_install:
  - pip install pytest pytest-cov pylint

install:
  - pip install .

script:
  - pylint dedec
  - pylint test/*.py
  - cd test && pytest --cov dedec

after_success:
  - bash <(curl -s https://codecov.io/bash)
